### ISSUE TITLE
test_long_system_call dies half way in python 2

### ISSUE THREAD

**Issue by oxplot** [oxplot/tamekit#1]
```
test_caught_timeout_in_thread (__main__.TimeoutAfterTests) ... ok
test_context_manager (__main__.TimeoutAfterTests) ... ok
test_custom_exc (__main__.TimeoutAfterTests) ... ok
test_decorator (__main__.TimeoutAfterTests) ... ok
test_delayed_use (__main__.TimeoutAfterTests) ... ok
test_delayed_use_decorator (__main__.TimeoutAfterTests) ... ok
test_exc_after_wrapped_code (__main__.TimeoutAfterTests) ... ok
test_long_system_call (__main__.TimeoutAfterTests) ... Traceback (most recent call last):
  File "test_tamekit.py", line 121, in <module>
    unittest.main()
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 333, in run
    result.addFailure(self, sys.exc_info())
  File "/usr/lib/python2.7/unittest/runner.py", line 74, in addFailure
    super(TextTestResult, self).addFailure(test, err)
  File "/usr/lib/python2.7/unittest/result.py", line 17, in inner
    if getattr(self, 'failfast', False):
tamekit.TimeoutError

```

**Comment by oxplot** [comment]
Py3 calls `_PyEval_SignalAsyncExc();` that Py2 doesn't (from *pystate.c):

```
/* Asynchronously raise an exception in a thread.
   Requested by Just van Rossum and Alex Martelli.
   To prevent naive misuse, you must write your own extension
   to call this, or use ctypes.  Must be called with the GIL held.
   Returns the number of tstates modified (normally 1, but 0 if `id` didn't
   match any known thread id).  Can be called with exc=NULL to clear an
   existing async exception.  This raises no exceptions. */

int
PyThreadState_SetAsyncExc(long id, PyObject *exc) {
    PyInterpreterState *interp = GET_INTERP_STATE();
    PyThreadState *p;

    /* Although the GIL is held, a few C API functions can be called
     * without the GIL held, and in particular some that create and
     * destroy thread and interpreter states.  Those can mutate the
     * list of thread states we're traversing, so to prevent that we lock
     * head_mutex for the duration.
     */
    HEAD_LOCK();
    for (p = interp->tstate_head; p != NULL; p = p->next) {
        if (p->thread_id == id) {
            /* Tricky:  we need to decref the current value
             * (if any) in p->async_exc, but that can in turn
             * allow arbitrary Python code to run, including
             * perhaps calls to this function.  To prevent
             * deadlock, we need to release head_mutex before
             * the decref.
             */
            PyObject *old_exc = p->async_exc;
            Py_XINCREF(exc);
            p->async_exc = exc;
            HEAD_UNLOCK();
            Py_XDECREF(old_exc);
            _PyEval_SignalAsyncExc();
            return 1;
        }
    }
    HEAD_UNLOCK();
    return 0;
}
```
